# Decession Tree


In [1]:
!pip install matplotlib

In [2]:
import numpy as np
# import matplotlib.pyplot as plt
import pandas as pd
# from matplotlib import pyplot as plt


iris = pd.read_csv('IRIS.csv')
#explore

In [2]:
print(iris)

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]


In [3]:
print(iris.shape)

(150, 5)


In [4]:
from sklearn import tree
X = [[0, 0], [1, 1]]
Y = [0, 1]
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X, Y)

In [5]:
clf.predict([[2., 2.]])
# iris([1])

array([1])

In [6]:
# from sklearn import tree
# iris = load_iris()
# X, y = iris.data, iris.target
# clf = tree.DecisionTreeClassifier()
# clf = clf.fit(X, y)

In [7]:
# iris['species'].replace(['Iris-setosa', 'Iris-virginica'],[0, 1], inplace=True)

In [13]:
# y=iris['species']
# x=iris.drop('species',axis=1)

In [14]:
# x

In [15]:
# y

In [16]:
# from sklearn import tree
# iris = iris()
# X, y = iris.data, iris.target
# clf = tree.DecisionTreeClassifier()
# clf = clf.fit(x, y)

In [17]:
# tree.plot_tree(clf)


In [18]:
#preprocessing

In [19]:
#  Feature Extraction and Engineering
features_names = ['sepal_length','sepal_width','petal_length','petal_width']
training_features = iris[features_names]
training_features

sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [20]:
outcome_name = ['species']
outcome_labels = iris[outcome_name]
outcome_labels

species
0       Iris-setosa
1       Iris-setosa
2       Iris-setosa
3       Iris-setosa
4       Iris-setosa
..              ...
145  Iris-virginica
146  Iris-virginica
147  Iris-virginica
148  Iris-virginica
149  Iris-virginica

[150 rows x 1 columns]

In [21]:

from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier()
model = classifier.fit(training_features, outcome_labels)

In [22]:
classifier

DecisionTreeClassifier()

In [23]:
# from sklearn.datasets import load_iris
# from sklearn import tree
# iris = load_iris()
# x, y = iris.data, iris.target
# x, y = iris.data, iris.target
# clf = tree.DecisionTreeClassifier()
# model = clf.fit(training_features, outcome_labels)

In [155]:
# from sklearn.metrics import classification_report, confusion_matrix
# print("Confusion matrix",confusion_matrix(training_features,outcome_labels))

In [25]:
pred_labels = model.predict(training_features)
actual_labels = np.array(outcome_labels['species'])
print(pred_labels)
print()
print(actual_labels)

['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor

In [26]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
print("Accuracy:\n")
accuracy_score(actual_labels,pred_labels)

Accuracy:



1.0

In [27]:
print("Confusion Matrix:\n")
confusion_matrix(actual_labels,pred_labels)

Confusion Matrix:



array([[50,  0,  0],
       [ 0, 50,  0],
       [ 0,  0, 50]], dtype=int64)

In [28]:
print("Classification Report:\n")
print(classification_report(actual_labels,pred_labels))

Classification Report:

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        50
Iris-versicolor       1.00      1.00      1.00        50
 Iris-virginica       1.00      1.00      1.00        50

       accuracy                           1.00       150
      macro avg       1.00      1.00      1.00       150
   weighted avg       1.00      1.00      1.00       150



##  loop the above process

In [56]:
# from sklearn.model_selection import train_test_split
# i=1
# x=0.5
# # test_sz=0.85
# test_sz=0.85
# for i in range(1,10):
#     x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.85-x)


In [58]:
#training the algorithm Here we would use Decession classifier
from sklearn.tree import DecisionTreeClassifier
classifier=DecisionTreeClassifier()
# model=classifier.fit(x_train,y_train)

# Decision Tree With Scikitlearn

In [2]:
!pip install matplotlib

In [2]:
import numpy as np
import matplotlib
from matplotlib import pyplot as plt
# import matplotlib.pyplot as plt
import pandas as pd
from sklearn.datasets import load_breast_cancer

SyntaxError: invalid syntax (matplotlib.py, line 10)

In [10]:
data = load_breast_cancer()
dataset=pd.DataFrame(data=data['data'],columns=data['feature_names'])
dataset

NameError: name 'load_breast_cancer' is not defined

In [3]:
from sklearn.model_selection import train_test_split
x=dataset.copy()
y=data['target']
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.33)

In [30]:
from sklearn.tree import DecisionTreeClassifier
# clf=DecisionTreeClassifier()
clf=DecisionTreeClassifier(ccp_alpha=0.01)
clf=clf.fit(x_train,y_train)

In [31]:
clf

DecisionTreeClassifier(ccp_alpha=0.01)

In [32]:
clf.get_params()

{'ccp_alpha': 0.01,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'random_state': None,
 'splitter': 'best'}

In [33]:
predictions=clf.predict(x_test)
predictions

array([0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1])

In [34]:
#show difference between tree that don't have stopping criteria and the one that does
clf.predict_proba(x_test)

array([[0.98360656, 0.01639344],
       [0.02183406, 0.97816594],
       [0.02183406, 0.97816594],
       [0.02183406, 0.97816594],
       [0.02183406, 0.97816594],
       [0.02183406, 0.97816594],
       [0.02183406, 0.97816594],
       [0.02183406, 0.97816594],
       [0.98360656, 0.01639344],
       [0.98360656, 0.01639344],
       [0.02183406, 0.97816594],
       [0.94117647, 0.05882353],
       [0.98360656, 0.01639344],
       [0.02183406, 0.97816594],
       [0.98360656, 0.01639344],
       [0.02183406, 0.97816594],
       [0.98360656, 0.01639344],
       [0.02183406, 0.97816594],
       [0.02183406, 0.97816594],
       [0.98360656, 0.01639344],
       [0.98360656, 0.01639344],
       [0.02183406, 0.97816594],
       [0.        , 1.        ],
       [0.375     , 0.625     ],
       [0.98360656, 0.01639344],
       [0.98360656, 0.01639344],
       [0.02183406, 0.97816594],
       [0.98360656, 0.01639344],
       [0.98360656, 0.01639344],
       [0.98360656, 0.01639344],
       [0.

In [35]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,predictions)

0.9468085106382979

In [36]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,predictions,labels=[0,1])

array([[ 63,   5],
       [  5, 115]], dtype=int64)

In [37]:
from sklearn.metrics import precision_score
precision_score(y_test,predictions)

0.9583333333333334

In [38]:
from sklearn.metrics import classification_report
print(classification_report(y_test,predictions,target_names=['malignant','benign']))

              precision    recall  f1-score   support

   malignant       0.93      0.93      0.93        68
      benign       0.96      0.96      0.96       120

    accuracy                           0.95       188
   macro avg       0.94      0.94      0.94       188
weighted avg       0.95      0.95      0.95       188



In [39]:
feature_names = x.columns
feature_names

Index(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error', 'fractal dimension error',
       'worst radius', 'worst texture', 'worst perimeter', 'worst area',
       'worst smoothness', 'worst compactness', 'worst concavity',
       'worst concave points', 'worst symmetry', 'worst fractal dimension'],
      dtype='object')

In [40]:
feature_importance = pd.DataFrame(clf.feature_importances_, index=feature_names).sort_values(0,)
feature_importance

0
mean radius              0.000000
worst concavity          0.000000
worst compactness        0.000000
worst smoothness         0.000000
worst area               0.000000
fractal dimension error  0.000000
symmetry error           0.000000
concave points error     0.000000
concavity error          0.000000
compactness error        0.000000
worst symmetry           0.000000
area error               0.000000
smoothness error         0.000000
texture error            0.000000
mean texture             0.000000
mean perimeter           0.000000
mean area                0.000000
mean smoothness          0.000000
perimeter error          0.000000
worst fractal dimension  0.000000
mean concavity           0.000000
mean concave points      0.000000
mean symmetry            0.000000
mean fractal dimension   0.000000
radius error             0.000000
mean compactness         0.000000
worst perimeter          0.034804
worst texture            0.042834
worst radius             0.125012
worst concave points     0.797350

In [41]:
features = list(feature_importance[feature_importance[0]>0].index)
features

['worst perimeter', 'worst texture', 'worst radius', 'worst concave points']

In [45]:
feature_importance.head(10).plot(kind='bar')

SyntaxError: invalid syntax (matplotlib.py, line 10)

In [46]:
from sklearn import tree
from matplotlib import pyplot as plt
fig = plt.figure(figsize=(25,20))
_=tree.plot_tree(clf,
                feature_names=feature_names,
                class_names={0:'Malignant',1:'Benign'},
                filled=True,
                fontsize=12)

SyntaxError: invalid syntax (matplotlib.py, line 10)

In [44]:
!pip install matplotlib