### 1) Intro to Python and Python IDEs


In [2]:
print('hello')

hello


In [6]:
#Variable in python
 # Data/Values can be stored in temporary storage spaces called Variables.
    
student = "Sam"
student

'Sam'

In [ ]:
# DataTypes in Python
# Every variable is associated with a data


##### Python Token (Smallest meaningful component in a Program)

In [ ]:
#Keywords are special reserved words

In [ ]:
# Identifiers
# Identifiers are names used for variables, functions or objects
###RULES
# No special character except_(underscore)
#Identifiers are case sensitive
#FirstLetter can not be a digit


In [1]:
#String Finding
s1 = 'This is a computer'
s1.find('computer')

10

In [3]:
fruits= "apple,orange,banana"
fruits.split(',')

['apple', 'orange', 'banana']

###  2) Data Structures in Python

In [ ]:
# Tuple in python
# Tuple is ordered collection of elements enclosed within()


In [9]:
tup_1 = [1,"a",True,2,"b",False]
tup_1[0]

1

In [17]:
#concatination 
tup_1=(1,2,3)
tup_2=(4,5,6)
tup_1+tup_2
#repeat n time
n=1
tup_1*n

(1, 2, 3)

In [ ]:
#LIST In Python
# List is an ordered collection of elements enclosed within []


In [18]:
#Reverse elements of a list
l1=[1,"a",2,"b",3,"c"]
l1.reverse()
l1

['c', 3, 'b', 2, 'a', 1]

In [19]:
#sorting a list
l2 = ["mango","apple","banana","guava","orange"]
l2.sort()
l2

['apple', 'banana', 'guava', 'mango', 'orange']

In [21]:
#Inserting element at a specified index
l3=[1,"a",2,"b",3,"c"]
l3.insert(1,"Sparta")
l3

[1, 'Sparta', 'a', 2, 'b', 3, 'c']

In [22]:
#concatenating Lists
l4 = [1,2,3]
l2 = ["apple","mango","orange"]
l4+l2


[1, 2, 3, 'apple', 'mango', 'orange']

In [26]:
#DICTIONARY
# Dictionary is an unordered collection of key-value pairs enclose with {}

fruit = {'apple':100,'mango':150,'orange':80}
#Extract Keys
fruit.keys()
#extract Value
fruit.values()

dict_values([100, 150, 80])

In [30]:
# Adding a new elements
fruit['banana'] = 50
fruit

{'apple': 100, 'mango': 150, 'orange': 80, 'banana': 50, 'Apple': 100}

In [33]:
#changing an existing element
fruit["apple"] = 120
fruit

{'apple': 120, 'mango': 150, 'orange': 80, 'banana': 50, 'Apple': 120}

In [34]:
#update one dictionary's element with another
fruit_1 = {'Apple':110,'banana':60}
fruit_2 = {'guava':40,'mango':80}
fruit_1.update(fruit_2)
fruit_1

{'Apple': 110, 'banana': 60, 'guava': 40, 'mango': 80}

In [35]:
# Popping an element
fruit_1.pop("guava")
fruit_1

{'Apple': 110, 'banana': 60, 'mango': 80}

In [ ]:
#SET in python
# set is an unordered and unindexed collection of elements enclosed with {}



In [36]:
#Update one dictionary's elements with another
s1={1,"a",True,2,"b",False}
s1.add("Hello")
s1

{1, 2, False, 'Hello', 'a', 'b'}

In [42]:
# Removing an element
s1.remove("Hello")
s1

{1, 2, False, 'a'}

In [44]:
#update multiple elements
s1.update([10,20,30])
s1

{1, 10, 2, 20, 30, False, 'a'}

In [45]:
# Union of two set
s2 = {2,"ab",3,"da"}
s1.union(s2)

{1, 10, 2, 20, 3, 30, False, 'a', 'ab', 'da'}

###  3) Flow Control Statements and Functions

###  4)Object Oriented Programming

### 5) Numpy, Pandas, Matplotlib and Seaborn

###  6)Linear Regression

###  7) Logistic Regression

###  8) Time Series

#  Python Library

In [1]:
 #Pandas:- For data manupulation
#numpy:- numerical computing (numerical python and is the core library for numeric and scientific computing)
#matplot lib:- for visualisation


In [2]:
# Single dimensional array
import numpy as np
n1 = np.array([10,20,30,40])
n1

array([10, 20, 30, 40])

In [4]:
#multi-dimensional Array
n2 = np.array([[10,20,30,40],[50,60,70,80]])
n2

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [5]:
#Initializing
n3 = np.zeros((1,2))
n3

array([[0., 0.]])

In [6]:
n4 = np.zeros((10,5))
n4

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
#initialize a specific number
n5=np.full((10,5),11)
n5

array([[11, 11, 11, 11, 11],
       [11, 11, 11, 11, 11],
       [11, 11, 11, 11, 11],
       [11, 11, 11, 11, 11],
       [11, 11, 11, 11, 11],
       [11, 11, 11, 11, 11],
       [11, 11, 11, 11, 11],
       [11, 11, 11, 11, 11],
       [11, 11, 11, 11, 11],
       [11, 11, 11, 11, 11]])

In [9]:
# array using a range
n6 = np.arange(10,36)
n6

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35])

In [11]:
# skip a specific number interval
n7 = np.arange(10,101,10)
n7

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [17]:
# initialize with ramdom number
n8 = np.random.randint(1,101,10)
n8

array([77, 48, 38, 74, 93, 76, 69, 18, 14,  1])

In [19]:
# checking the shape of numpy & its shape
n5.shape

(10, 5)

In [26]:
n5.shape=(5,10)
n5

array([[11, 11, 11, 11, 11, 11, 11, 11, 11, 11],
       [11, 11, 11, 11, 11, 11, 11, 11, 11, 11],
       [11, 11, 11, 11, 11, 11, 11, 11, 11, 11],
       [11, 11, 11, 11, 11, 11, 11, 11, 11, 11],
       [11, 11, 11, 11, 11, 11, 11, 11, 11, 11]])

###  join numpy array

In [40]:
#Vstack() //vertical
import numpy as np
# n1 = np.array([[1,2,3,4,5],[6,7,8,9,0]])
# n2 = np.array([[0,9,8,7,6],[5,4,3,2,1]])
n1 = np.array([1,2,3,4,5,7,8,9,0])
n2 = np.array([0,9,8,7,6,4,3,2,1])
np.vstack((n1,n2))

array([[1, 2, 3, 4, 5, 7, 8, 9, 0],
       [0, 9, 8, 7, 6, 4, 3, 2, 1]])

In [41]:
#hstack() //horizontal staack
np.hstack((n1,n2))


array([1, 2, 3, 4, 5, 7, 8, 9, 0, 0, 9, 8, 7, 6, 4, 3, 2, 1])

In [42]:
# column_stack
np.column_stack((n1,n2))


array([[1, 0],
       [2, 9],
       [3, 8],
       [4, 7],
       [5, 6],
       [7, 4],
       [8, 3],
       [9, 2],
       [0, 1]])

In [45]:
# Intersection & difference
np.intersect1d(n1,n2)

array([0, 1, 2, 3, 4, 7, 8, 9])

In [46]:
 np.setdiff1d(n1,n2)

array([5])

In [47]:
np.setdiff1d(n2,n1)

array([6])

###  mathematical functions

In [48]:
np.sum([n1,n2])

79

In [51]:
n1

array([1, 2, 3, 4, 5, 7, 8, 9, 0])

In [52]:
#saving numpy
np.save('my_numpy_1',n1)

In [55]:
num = np.load('my_numpy_1.npy')
num

array([1, 2, 3, 4, 5, 7, 8, 9, 0])

# Pandas

In [57]:
#Pandas Stands for Panel Data and is the core library for data manipulation and data analysis.


In [58]:
import pandas as pd
s1=pd.Series([1,2,3,4,5])
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [60]:
#changing index
import pandas as pd
s1 = pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])
s1

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [64]:
#series Object from Dictionary
pd.Series({'key':'value','a':10,'b':20,'c':30})


key    value
a         10
b         20
c         30
dtype: object

In [68]:
pd.Series({'key':'values','a1':101,'a2':102,'a3':103,'a4':104,'a5':105},index=['a','b','c','d','e'])

a    NaN
b    NaN
c    NaN
d    NaN
e    NaN
dtype: object

In [69]:
# extracting individual elements
s1=pd.Series([1,2,3,4,5,6,7,8,9])
s1[3]

4

In [71]:
#extracting elements from back
s1[-3:]

6    7
7    8
8    9
dtype: int64

In [72]:
s1[:4]

0    1
1    2
2    3
3    4
dtype: int64

In [74]:
# Basic math Operation on series

In [75]:
#Adding a scalar value to Series Elements
s1+5

0     6
1     7
2     8
3     9
4    10
5    11
6    12
7    13
8    14
dtype: int64

In [82]:
# Adding two Series Objects
s2=pd.Series([10,20,30,40,50,60,70,60,80])
s1+s2

0    11
1    22
2    33
3    44
4    55
5    66
6    77
7    68
8    89
dtype: int64

In [83]:
#Creating a Dataframe
import pandas as pd
pd.DataFrame({"Name":['Bob','Sam','Anne'],"Marks":[76,25,92]})

Name  Marks
0   Bob     76
1   Sam     25
2  Anne     92

In [85]:
# Dataframe in-built function
# 1)head() :- we use for to retrive first 5 rows of any dataset 
# 2)describe() :- To show the general data about dataset
# 3)tail() :- to retrive last 5 rows of a dataset
# 4)shape() :- To show the shape of dataset
    

In [108]:
iris = pd.read_csv('iris.csv')

In [109]:
iris.head() #to show first 5 record


sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [110]:
# To show the last 5 data
iris.tail()  

sepal_length  sepal_width  petal_length  petal_width         species
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

In [111]:
# To Show the Shape of the dataset i.e. number of rows & columns
iris.shape

(150, 5)

In [105]:
# To Show the basic Informations
Ires.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [112]:
# To display a specific rows use iloc
iris.iloc[5:11 ,2:]

petal_length  petal_width      species
5            1.7          0.4  Iris-setosa
6            1.4          0.3  Iris-setosa
7            1.5          0.2  Iris-setosa
8            1.4          0.2  Iris-setosa
9            1.5          0.1  Iris-setosa
10           1.5          0.2  Iris-setosa

In [114]:
#
iris.loc[1:10,('petal_length')]

1     1.4
2     1.3
3     1.5
4     1.4
5     1.7
6     1.4
7     1.5
8     1.4
9     1.5
10    1.5
Name: petal_length, dtype: float64

In [115]:
# Droping Column
iris.drop('petal_length',axis=1)

sepal_length  sepal_width  petal_width         species
0             5.1          3.5          0.2     Iris-setosa
1             4.9          3.0          0.2     Iris-setosa
2             4.7          3.2          0.2     Iris-setosa
3             4.6          3.1          0.2     Iris-setosa
4             5.0          3.6          0.2     Iris-setosa
..            ...          ...          ...             ...
145           6.7          3.0          2.3  Iris-virginica
146           6.3          2.5          1.9  Iris-virginica
147           6.5          3.0          2.0  Iris-virginica
148           6.2          3.4          2.3  Iris-virginica
149           5.9          3.0          1.8  Iris-virginica

[150 rows x 4 columns]

In [116]:
#Droping rows
iris.drop([1,2,3],axis=0)

sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
5             5.4          3.9           1.7          0.4     Iris-setosa
6             4.6          3.4           1.4          0.3     Iris-setosa
7             5.0          3.4           1.5          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[147 rows x 5 columns]

In [117]:
#Mean
iris.mean()

C:\Users\subha\AppData\Local\Temp\ipykernel_10328\2269409905.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  iris.mean()


sepal_length    5.843333
sepal_width     3.054000
petal_length    3.758667
petal_width     1.198667
dtype: float64

In [118]:
#minimum
iris.min()

sepal_length            4.3
sepal_width             2.0
petal_length            1.0
petal_width             0.1
species         Iris-setosa
dtype: object

In [119]:
#median
iris.median

<bound method NDFrame._add_numeric_operations.<locals>.median of      sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]>

In [120]:
# Maximum
iris.max()

sepal_length               7.9
sepal_width                4.4
petal_length               6.9
petal_width                2.5
species         Iris-virginica
dtype: object

In [121]:
# More Function
def half(s):
    return s*0.5
iris[['sepal_length','petal_length']].apply(half)

sepal_length  petal_length
0            2.55          0.70
1            2.45          0.70
2            2.35          0.65
3            2.30          0.75
4            2.50          0.70
..            ...           ...
145          3.35          2.60
146          3.15          2.50
147          3.25          2.60
148          3.10          2.70
149          2.95          2.55

[150 rows x 2 columns]

In [122]:
#Value_counts()
iris['sepal_length'].value_counts()

5.0    10
5.1     9
6.3     9
5.7     8
6.7     8
5.8     7
5.5     7
6.4     7
4.9     6
5.4     6
6.1     6
6.0     6
5.6     6
4.8     5
6.5     5
6.2     4
7.7     4
6.9     4
4.6     4
5.2     4
5.9     3
4.4     3
7.2     3
6.8     3
6.6     2
4.7     2
7.6     1
7.4     1
7.3     1
7.0     1
7.1     1
5.3     1
4.3     1
4.5     1
7.9     1
Name: sepal_length, dtype: int64

In [125]:
#sort_values()
iris.sort_values(by='sepal_length')

sepal_length  sepal_width  petal_length  petal_width         species
13            4.3          3.0           1.1          0.1     Iris-setosa
42            4.4          3.2           1.3          0.2     Iris-setosa
38            4.4          3.0           1.3          0.2     Iris-setosa
8             4.4          2.9           1.4          0.2     Iris-setosa
41            4.5          2.3           1.3          0.3     Iris-setosa
..            ...          ...           ...          ...             ...
122           7.7          2.8           6.7          2.0  Iris-virginica
118           7.7          2.6           6.9          2.3  Iris-virginica
117           7.7          3.8           6.7          2.2  Iris-virginica
135           7.7          3.0           6.1          2.3  Iris-virginica
131           7.9          3.8           6.4          2.0  Iris-virginica

[150 rows x 5 columns]

#  MatplotLib

In [1]:
import numpy as np
from matplotlib import pyplot as plt


SyntaxError: invalid syntax (matplotlib.py, line 10)

In [127]:
pip install matplotlib


Note: you may need to restart the kernel to use updated packages.


## Seaborn plot

In [2]:
import pandas as pd
iris = pd.read_csv('iris.csv')

In [5]:
import seaborn as sns
from matplotlib import pyplot as plt
fmri = sns.load_dataset('iris')
fmri.head()

SyntaxError: invalid syntax (matplotlib.py, line 10)

In [7]:
!pip install matplotlib

In [10]:
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns
# from matplotlib import pyplot as plt
fmri = sns.load_dataset('fmri')
fmri.head()

SyntaxError: invalid syntax (matplotlib.py, line 10)

In [11]:
import seaborn as sns
from matplotlib import pyplot as plt
fmri = sns.load_dataset('fmri')
fmri.head()

SyntaxError: invalid syntax (matplotlib.py, line 10)